### ISSUE TITLE
onException async/await fails to catch error in promise

### ISSUE THREAD

**Issue by jcjolley** [k1r0s/kaop-ts#34]
http://plnkr.co/edit/jBF9kqe7NIbjwXaZSWWS?p=preview
![image](https://user-images.githubusercontent.com/2086176/30869469-6f9ab7f0-a29e-11e7-9437-08ffaa9cb4e9.png)

onException doesn't work on 'es7 async/await' style async methods, at least not how I have it done in the plunker.  Is this on the roadmap at all?  I figure it's likely I'm just doing it wrong, but wanted to check.

Thanks again for the excellent lib!

**Comment by k1r0s** [comment]
Hi @jcjolley Async catch don't work even without async/await. Think about you're trowing an exception on an async context while `onException` join point is only wrapping a method call with try catch looking for **synchronous** (note that) unhandled exceptions.

You have to see what async/await is doing on the background to properly understand this problem. 

Since async/await is performing an async task by returning a promise on the same spot you be able to capture that promise after the method has been executed, so the work arround is **to use "afterMethod" join point to subscribe for unhandled exceptions:**

```javascript
export const handleErrorAfterAsync = afterMethod(function(meta) {
  meta.result.catch(whatEverYouThrow => console.log(whatEverYouThrow))
})
```

Then you will be able to run that function when that async method throws an exception. AKA the returning promise was not fulfilled because some error, so catch is triggered.

**Comment by k1r0s** [comment]
Thanks a lot @jcjolley to point it
