### ISSUE TITLE
Set Up on browser

### ISSUE THREAD

**Issue by bernardmizzi** [k1r0s/kaop-ts#85]
For this library to be used on the browser, do I have to download the src folder and import from index.ts?

**Comment by k1r0s** [comment]
Hi @bernardmizzi. You will need to use umd bundle which is located on `dist/kaop-ts.umd.js` when you build the project.

Alernatively you can use cdn sources as unpkg: https://unpkg.com/kaop-ts

so if you include the following script in your webpage:

```html
<script src="https://unpkg.com/kaop-ts@3.1.3/dist/kaop-ts.umd.js"></script>
``` 
the whole library will be available under `window.kaopTs` object

**Comment by k1r0s** [comment]
Anyways I wouldn't recommend to use kaop-ts (ES6+ version) on browsers since you will need many many tools to access its features. 

Try kaop instead: https://github.com/k1r0s/kaop

**Comment by bernardmizzi** [comment]
Does the setu you explained work also for kaop?

**Comment by k1r0s** [comment]
absolutely, thanks!

**Comment by bernardmizzi** [comment]
Thanks a lot mate! Just one last question, I've discovered that a lot of AOP javascript libraries make use of method overriding like this:

```
var nameOfTheDesiredFunction = 'functionA'
var func = window[nameOfTheDesiredFunction] 
window[nameOfTheDesiredFunction]  = function(){
       ...
      //before functions
      var returnValue = func.apply(this, arguments)
       ...
       //after functions
      
       return returnValue
}
```

Currently I'm searching for AOP libraries so that I use a profiler and compare their performance. Does kaop make use of the above technique?

**Comment by k1r0s** [comment]
Its way more complex. On example above, for example, you cannot deal with asychronous advices and many other goodies.. With this library you can, for example, attach advices that do async stuff and then execute annotated method which is not possible with other AOP libraries.

```javascript
const { reflect, createClass } = require("kaop")

const delay = reflect.advice(meta => setTimeout(meta.commit, 1000));

const Car = createClass({
  startEngine: [delay, function() {
    console.log("engine started!")
  }]
});

const carInstance = new Car;
carInstance.startEngine(); // after 1s log is printed
```

kaop-ts (this library) provides ES7 Decorators to attach advices to ES6 Classes and makes use of `kaop` under the hood.

kaop (core) provides all the functionalities. But, of course, it only works on top of OOP, so it provides a full toolbelt of OOP stuff like createClass, extend, override, reflection, etc..

Anyways, kaop drives you to create new interfaces rather than editing native objects. 

```javascript
import { extend } from 'kaop'

// Instead of modifing Array.prototype
const MyArray = extend(Array, {
  includes(value) {
    return this.indexOf(value) > -1;
  }
});

const arr = new MyArray(1, 2, 3, 4);

arr.includes(2); // true
arr.includes(5); // false
```

And, again, if you want do patch native JS interfaces like window, the best approach is to wrap it into custom classes rather than editing native prototypes.

Here is an example about some advance capabilities: https://github.com/k1r0s/kaop/blob/master/showcase.js

Glad you made a benchmark over this :)

If you have anyother questions just ask

feel free to close the issue

**Comment by bernardmizzi** [comment]
So on the browser I can know attach advises by inserting window.kaopTs.beforeMethod(), do I have to pass any arguments? Is this inserted before a declared method? Because since now I am using it on the browser I thought that there may exist some alterations.

**Comment by k1r0s** [comment]
You can only use kaop-ts either with babel or typescript. You cannot use it on browsers because you need ES6 classes and they don't exists in browsers yet.

`beforeMethod` is a decorator and you cannot use it over browsers because you need to use it along with `@` syntax over a specific method and sadly __decorators are not an standard yet__ thats why you need special tools.

You can find more information about this syntax here: https://medium.com/google-developers/exploring-es7-decorators-76ecb65fb841

Although you can use it on browsers with special tools and babel (or TS) enabled like this: https://jsbin.com/bogecojuvi/edit?js,console

I recomend use `kaop` instead which uses standard JS code for AOP :)

**Comment by k1r0s** [comment]
This code works on browsers (tested with crome)
https://jsbin.com/hosecilefe/edit?js,console

```javascript
const { createClass, reflect } = kaop;

const increaseMinimumAllowed = reflect.advice(meta => {
    if(!meta.exception) return;
    const exception = meta.handle();
    console.warn(exception.message);
    meta.result = 500;
})



const DummyConsultancyCompany = createClass({
    developerYearlySalaryRevision: [function (amountRequested) {
        if(amountRequested > 3000) throw new Error("For the last time, NO!");
        return amountRequested;
    }, increaseMinimumAllowed]
})

const inst = new DummyConsultancyCompany

const requested1 = 2000;
const result1 = inst.developerYearlySalaryRevision(requested1);

console.log("Anna asked for "+requested1+"$ and she gets "+result1+"$")

const requested2 = 4000;
const result2 = inst.developerYearlySalaryRevision(requested2)

console.log("Sara asked for "+requested2+"$ and she gets "+result2+"$")
```

**Comment by bernardmizzi** [comment]
Thankyou, the above code works. But can I apply the same technique to my functions. Suppose I have a declared function (declared out of a class) and I want to check its return value or arguments, can the same technique be applied?

**Comment by k1r0s** [comment]
The same API applies for `kaop` and `kaop-ts` https://github.com/k1r0s/kaop-ts/blob/master/docs/api.md#metadata

So you can read/write arguments, access return, access instance, method, etc etc.. skip method execution, access exceptions, anything :)

**Comment by k1r0s** [comment]
> Suppose I have a declared function (declared out of a class)

In AOP you cannot annotate functions separately, it has to be class methods
